### ISSUE TITLE
Fix tagline url

### ISSUE THREAD

**Issue by ShepherdJerred** [vitalk/ansible-secure-ssh#9]
The tagline URL current points to a 404 page. It should be changed to a valid URL (Probably https://galaxy.ansible.com/vitalk/secure-ssh).

To clarify, this is what I mean by tagline
<img width="716" alt="Screen Shot 2019-11-30 at 12 51 27 PM" src="https://user-images.githubusercontent.com/3904778/69905940-2ec2ba80-1370-11ea-9fd4-1709427f41ac.png">

Current page:
<img width="1548" alt="Screen Shot 2019-11-30 at 12 50 09 PM" src="https://user-images.githubusercontent.com/3904778/69905926-fa4efe80-136f-11ea-8ccd-de378182b52c.png">

**Comment by vitalk** [comment]
Thank you @ShepherdJerred. I updated tagline as you suggested. Have a nice day!
